package com.example.hexagonal.application.error;

public enum ErrorCode {
    MISSING_HEADER,
    VALIDATION_ERROR,
    MISSING_REQUEST_VALUE,
    INVALID_API_VERSION,
    UNSUPPORTED_MEDIA_TYPE,
    METHOD_NOT_ALLOWED,
    INVALID_JSON,
    INVALID_REQUEST_BODY,
    CONTENT_NOT_FOUND,
    PROVIDER_UNAVAILABLE,
    BUSINESS_ERROR,
    APPLICATION_ERROR,
    DOMAIN_ERROR,
    ROUTE_NOT_FOUND,
    UNEXPECTED_ERROR
}
